package.json: switch from webpack-dev-server to webpack serve (#451)
because #439 updated webpack-cli from 3.x to 4.x and the command changed

webpack-dev-server still gets installed, but fails with `Error: Cannot find module 'webpack-cli/bin/config-yargs'`