React - switch to React 17, enable StrictMode (#2925)
* React - switch to react 17

No-Issue

* React - enable StrictMode

https://reactjs.org/docs/strict-mode.html

* Fix type error - ReactNodeArray doesn't match any[]

    src/components/patternfly-wrappers/stateful-dropdown.tsx:63:9 - error TS2322: Type 'ReactNodeArray' is not assignable to type 'any[]'.

    63         dropdownItems={items}
              ~~~~~~~~~~~~~

      node_modules/@patternfly/react-core/dist/esm/components/Dropdown/Dropdown.d.ts:11:5
        11     dropdownItems?: any[];
              ~~~~~~~~~~~~~
        The expected type comes from property 'dropdownItems' which is declared here on type 'IntrinsicAttributes & DropdownProps & { children?: ReactNode; }'

    Found 1 error in src/components/patternfly-wrappers/stateful-dropdown.tsx:63

* Router: fix Suspense fallback invocation